# Generated by Django 3.0.3 on 2020-03-07 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumb',
            field=models.FileField(default=datetime.datetime(2020, 3, 7, 14, 49, 49, 625607, tzinfo=utc), upload_to=gallery.models.get_file_path),
            preserve_default=False,
        ),
    ]
