# Generated by Django 3.0.3 on 2020-03-07 15:45

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='thumb',
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo_org',
            field=models.FileField(default='dummy_img', upload_to=gallery.models.get_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo_size_240',
            field=models.FileField(blank=True, null=True, upload_to=gallery.models.get_file_path),
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo_size_720',
            field=models.FileField(blank=True, null=True, upload_to=gallery.models.get_file_path),
        ),
    ]
