# Generated by Django 3.0.3 on 2020-03-08 13:46

from django.db import migrations
import django_resized.forms
import gallery.utility_methods


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_gallery_photo_org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1200, 675], upload_to=gallery.utility_methods.get_file_path),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo_size_240',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[240, 135], upload_to=gallery.utility_methods.get_file_path),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo_size_720',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[720, 405], upload_to=gallery.utility_methods.get_file_path),
        ),
    ]
